name: Run psuedocode

on:
 workflow_dispatch:
    inputs:
      comp:
        description: 'Component to run'
        required: true
        default: 'comp1'
        type: choice
        options:
          - comp1
          - comp2
          - comp4
  
# A workflow run is made up of one or more jobs that can run sequentially
jobs:
  jmeter_API_job:
# This job will run on AWS ECS API Runner in sequence 
    runs-on: ecsrunner
    
# Git Checks-out our repository      
    name: JMeter Test Execution
    steps:   
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install requests boto3 pandas openpyxl

   # Run the Jmeter test cases
    - name: Running JMeter for Jmeter-API-script-1
      run: |
        comp=comp1
        echo "Component selected: $comp"
        in_section=false
        while IFS= read -r line; do
          if [[ $line == "$comp:" ]]; then
            in_section=true
            continue
          elif [[ $line == *:* ]]; then
            in_section=false
          fi

          if $in_section; then
            echo "Running script: $line"
            jmeter -n -t $line
            echo "Running JMeter HTML"
            jmeter -Jjmeter.reportgenerator.exporter.html.series_filter="((T[0-9] {1,3}_))" -g DeterAPI/SampleAPIjtl1.jtl -o DeterAPI/HTMLReport1
          fi
        done < scripts_to_run.txt
       
    
